### ISSUE TITLE
项目跑不起来

### ISSUE THREAD

**Issue by jiangfu204** [aRootNotRoot/XYQ-offline#1]
项目跑不起来，不知道为什么会报表不存在的错误。这里项目会自动创建数据库和表么

异常信息：java.sql.SQLSyntaxErrorException: Table/View 'SHAPE' does not exist.

**Comment by jiangfu204** [comment]
项目引用问题，已经解决了

**Comment by aRootNotRoot** [comment]
项目wiki里有需要配置的数据，也可以直接从GoogleDrive下载完整工程导入部署来运行
 

Sent: Wednesday, August 15, 2018 at 4:31 AM
